version: '2'

services:
  customer:
    image: coilz/web-store-customer
    depends_on:
      - zookeeper
      - kafka

  shopping:
    image: coilz/web-store-shopping
    depends_on:
      - zookeeper
      - kafka

  readmodels:
    image: coilz/web-store-readmodels
    depends_on:
      - zookeeper
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.13.103
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock