version: '2'

services:

  customer:
    image: coilz/web-store-customer-api
    ports:
      - "5900:5000"
    depends_on:
      - db
      - zookeeper
      - kafka
    environment:
      DB_CONNECTION: postgres://db:5432
      ASPNETCORE_ENVIRONMENT: Development

  shopping:
    image: coilz/web-store-shopping-api
    ports:
      - "5901:5000"
    depends_on:
      - db
      - zookeeper
      - kafka
    environment:
      DB_CONNECTION: postgres://db:5432
      ASPNETCORE_ENVIRONMENT: Development

  readmodels:
    image: coilz/web-store-readmodels-api
    ports:
      - "5902:5000"
    depends_on:
      - db
      - zookeeper
      - kafka
    environment:
      DB_CONNECTION: postgres://db:5432
      ASPNETCORE_ENVIRONMENT: Development

  logistics:
    image: coilz/web-store-logistics-api
    ports:
      - "5903:5000"
    depends_on:
      - db
      - zookeeper
      - kafka
    environment:
      DB_CONNECTION: postgres://db:5432
      ASPNETCORE_ENVIRONMENT: Development

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.13.103
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock